### PR TITLE
JI-5612 — Sort the Paragraphs: Disabled after submit and Start Over — review

### PR DESCRIPTION
**Pull request by Gwenillia**
revert #47 and setViewState to task on reset

### CODE REVIEW

**Comment by VildeStabell** [comment]
This solves the discovered bugs, but now the "show solution" and "retry" buttons are not switched out for "submit" when resetting outside of the retry button

**Comment by Gwenillia** [comment]
True. I don't know how to change the PR from Open to Draft 😓 I'll check it anyways, thanks

**Comment by Gwenillia** [comment]
think it's solved now :c

**Comment by otacke** [comment]
@Gwenillia @VildeStabell I'll test this now, but could you please share the acceptance criteria of JI-5612, so I can make sure those are followed, too? I don't have access ... :-(

**Comment by VildeStabell** [comment]
Seems to work as intended now, good job ^^ It's good to go, unless @otacke finds anything

**Comment by Gwenillia** [comment]
@VildeStabell @otacke 
To test the current AC you need an H5P.com account I think 🤔 

But you probably can test this : 

1. create a sort the paragraph content with default settings
2. click on on and click on another to change them (no keyboard, no drag and drop)
3. leave and resume it
4. Trigger the resetTask() function (clicking on retry should do it but here we trigger it differently than retry button which may create some differences maybe ?) 
5. again switch 2 pargraphs positions with click only

**Comment by otacke** [comment]
That rest button on H5P.com uses the `resetTask` function defined in the Question Type contract. You can use that anywhere using `H5P.instances[0].resetTask()` in the browser's dev console (where number is the index of the instance in case there's more than one).

**Comment by otacke** [comment]
Seems to be working nicely, but I am not sure if I understand what the issue was.

Introcucing an extra callback doesn't seem to be necessary at all, is it -  and it will called for every state change, not just for (re)setting to `task`. One doesn't notice, but when the state is set to the solutions view , the callback will first handle the buttons in the `onViewStateChange` handler and hide the retry button, just to show it an instance afterwards when `checkAnswer` is called to rebuild the state.

Without changing the mechanism that is used, couldn't one simply add     
```
this.showButton('check-answer');
this.hideButton('show-solution');
this.hideButton('try-again');
```
to `resetTask`? And when that is done, one can remove the same three lines (and       `this.trigger('resize');`) from the retry button callback that calls `resetTask` anyway.

**Comment by Gwenillia** [comment]
Yup added them to resetTask.

**Comment by otacke** [comment]
Excellent! I only removed triggering a resize from the retry button callback, because that's done in `resetTask` anyway - old "my bad", not yours.

**Pull request merged**
