### PR TITLE
JI-5492 — Sort paragraphs state not fully reset

### PR DESCRIPTION
**Pull request by Gwenillia**
Seems that when resetTask is triggered, it wasn't emptying the previous state

### CODE REVIEW

**Comment by otacke** [comment]
It was not no. But it shuffles the items. Are you up for also resetting the state when you reload the content afterwards? I think resetting the `previousState` variable will not suffice then. Returning `undefined` in `getCurrentState` doesn't override existing states in the H5P integration, does it?

**Comment by Gwenillia** [comment]
triggering this.content.reset() before seems to do the job better, when resetting task it seems to shuffle now, thanks for pointing this out. In fact we want to shuffle when resetTask is triggered and when refreshing

**Comment by otacke** [comment]
I am still not sure what the issue is. As far as I can see, content is always properly shuffled when calling `resetTask` regardless of the value of `this.previousState`.

**Comment by Languafe** [comment]
It seems like setting `this.previousState = {}` can be done before or after calling `this.content.reset()` with the same result.

The reason we need to set the previousState to an empty object is to ensure that `getCurrentState` returns undefined after resetting.

**Comment by otacke** [comment]
Now I see, the guard at https://github.com/otacke/h5p-sort-paragraphs/blob/master/src/scripts/h5p-sort-paragraphs.js#L503-L505 has an `&&`, not an `||`, so checking `getAnswerGiven` is not enough ...

Sorry for stalling, my bad.

Note though that returning `undefined` in `getCurrentState` does not erase previous states in the H5P integration unless you have secretly changed how H5P core works, so after refreshing the page, there will still be a previous state - and that may be valid for multiple content types, not just Sort the Paragraphs. If that is what you ultimately want, the return value of `getCurrentState` (after a reset) should be `{}` here.

**Comment by Languafe** [comment]
You are most certainly correct on your last point, thank you very much for pointing that out. I verified this behavior in Wordpress.

**Comment by otacke** [comment]
So, H5P.com is really running a custom version of H5P core that differs in that regard?

**Comment by Languafe** [comment]
Not really, but the persisted content state could be reset in other ways.

**Comment by otacke** [comment]
Could be that the reset button also clears the state, yes. In that case, returning `undefined` would be enough - and prevent storing all the useless entries for `{}` inside the database.

**Pull request merged**
